### ISSUE TITLE
Feature request: Customize the string on the product output

### ISSUE THREAD

**Issue by mantrasong** [Syrchalis/UniversalFermenter#5]
I want to be able to have multiple inputs produce the same output, so that the user can control what products are being consumed. 

For example, if I can use several different types of wood to fuel my charcoal pit, but I don't want to use all of them, I want several recipes that the user can pick from (i.e. "cherry wood charcoal", "wood charcoal", "ebony charcoal")

(The goal is allowing finer control over what can be put in to produce a single output. A bills style or checkbox style system will also work, but is probably harder)

**Comment by Syrchalis** [comment]
Added.
